### ISSUE TITLE
Failing to list peers and identity, cjdns v 19.1

### ISSUE THREAD

**Issue by vhgarandil** [neilalexander/vyatta-cjdns#5]
kris@ubnt:~$ show interfaces cjdns tun0 peers
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-readconf", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 24 column 21 (char 669)
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-readconf", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 24 column 21 (char 669)
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-peerstats", line 69, in <module>
    cjdns = connecttoadmin(bindaddress[0], bindaddress[1], bindpassword)
IndexError: list index out of range
kris@ubnt:~$ show interfaces cjdns tun0 identity
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-readconf", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 24 column 21 (char 669)
kris@ubnt:~$ configure
[edit]
kris@ubnt# set interfaces cjdns tun0 admin-bind-address 127.0.0.1:64901
[edit]
kris@ubnt# set interfaces cjdns tun0 admin-password puf6ukkfzsrvgf06sll4tm4w34zzyqj
[edit]
kris@ubnt# commit
[ interfaces cjdns tun0 admin-bind-address 127.0.0.1:64901 ]
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-updateconf", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 24 column 21 (char 669)

[ interfaces cjdns tun0 admin-password puf6ukkfzsrvgf06sll4tm4w34zzyqj ]
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyatta-cjdns-updateconf", line 9, in <module>
    data = json.load(data_file)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 24 column 21 (char 669)

Commit failed
[edit]
kris@ubnt#

**Comment by vhgarandil** [comment]
After doing debugging it appears to be a fluke and not a systemic failure.
Not reproducible.
